name: 'AWS Secrets Manager Reader'
description: Github Action to read a secret value from AWS Secret Manager'
author: 'Tibo Delor'
inputs:
  secret-id:
    required: true
    description: 'Either ARN or friendly name of the secret'
  version-id:
    required: false
    description: 'Version id of the secret'
  version-stage:
    required: false
    description: 'Version stage of the secret'
    
  mask-value:
    required: false
    description: 'Assume the secret is JSON and mask all JSON object values, even the nested ones'
    default: true
  mask-json-values:
    required: false
    description: 'Assume the secret is JSON and mask all JSON object values, even the nested ones'
    default: false
  keys-as-env-vars:
    required: false
    description: 'Assume the secret is a JSON object and export the keys as env variables.'
    default: false
  keys-as-outputs:
    required: false
    description: 'Assume the secret is a JSON object and export the keys as env variables.'
    default: false
  append-to-env-file:
    required: false
    description: 'Assume the secret is a JSON object and append the key values in an env file. The value is the path to the file.'

outputs:
  secret: 
    description: 'Secret String return by AWS'
branding:
  icon: 'lock'  
  color: 'green'
runs:
  using: 'node16'
  main: 'dist/index.js'
